ERROR - 2023-06-16 18:26:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /Applications/MAMP/htdocs/codeigniter4/system/Database/MySQLi/Connection.php:174
Stack trace:
#0 /Applications/MAMP/htdocs/codeigniter4/system/Database/MySQLi/Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'sistema_db', 3306, '', 0)
#1 /Applications/MAMP/htdocs/codeigniter4/system/Database/BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/codeigniter4/system/Database/BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/codeigniter4/app/Models/CrudModel.php(7): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#4 /Applications/MAMP/htdocs/codeigniter4/app/Controllers/Crud.php(10): App\Models\CrudModel->listarNombres()
#5 /Applications/MAMP/htdocs/codeigniter4/system/CodeIgniter.php(934): App\Controllers\Crud->listado()
#6 /Applications/MAMP/htdocs/codeigniter4/system/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#7 /Applications/MAMP/htdocs/codeigniter4/system/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/codeigniter4/index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /Applications/MAMP/htdocs/codeigniter4/system/Database/MySQLi/Connection.php:218
Stack trace:
#0 /Applications/MAMP/htdocs/codeigniter4/system/Database/BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/codeigniter4/system/Database/BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/codeigniter4/app/Models/CrudModel.php(7): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#3 /Applications/MAMP/htdocs/codeigniter4/app/Controllers/Crud.php(10): App\Models\CrudModel->listarNombres()
#4 /Applications/MAMP/htdocs/codeigniter4/system/CodeIgniter.php(934): App\Controllers\Crud->listado()
#5 /Applications/MAMP/htdocs/codeigniter4/system/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /Applications/MAMP/htdocs/codeigniter4/system/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/codeigniter4/index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-16 18:26:31 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 427.
 1 SYSTEMPATH/Database/BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/CrudModel.php(7): CodeIgniter\Database\BaseConnection->query('SELECT * FROM users')
 3 APPPATH/Controllers/Crud.php(10): App\Models\CrudModel->listarNombres()
 4 SYSTEMPATH/CodeIgniter.php(934): App\Controllers\Crud->listado()
 5 SYSTEMPATH/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 6 SYSTEMPATH/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-16 18:29:48 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /Applications/MAMP/htdocs/codeigniter4/system/Database/MySQLi/Connection.php:174
Stack trace:
#0 /Applications/MAMP/htdocs/codeigniter4/system/Database/MySQLi/Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'sistema_db', 3306, '', 0)
#1 /Applications/MAMP/htdocs/codeigniter4/system/Database/BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/codeigniter4/system/Database/BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/codeigniter4/app/Models/CrudModel.php(7): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#4 /Applications/MAMP/htdocs/codeigniter4/app/Controllers/Crud.php(10): App\Models\CrudModel->listarNombres()
#5 /Applications/MAMP/htdocs/codeigniter4/system/CodeIgniter.php(934): App\Controllers\Crud->listado()
#6 /Applications/MAMP/htdocs/codeigniter4/system/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#7 /Applications/MAMP/htdocs/codeigniter4/system/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/codeigniter4/index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /Applications/MAMP/htdocs/codeigniter4/system/Database/MySQLi/Connection.php:218
Stack trace:
#0 /Applications/MAMP/htdocs/codeigniter4/system/Database/BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/codeigniter4/system/Database/BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/codeigniter4/app/Models/CrudModel.php(7): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#3 /Applications/MAMP/htdocs/codeigniter4/app/Controllers/Crud.php(10): App\Models\CrudModel->listarNombres()
#4 /Applications/MAMP/htdocs/codeigniter4/system/CodeIgniter.php(934): App\Controllers\Crud->listado()
#5 /Applications/MAMP/htdocs/codeigniter4/system/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /Applications/MAMP/htdocs/codeigniter4/system/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/codeigniter4/index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-16 18:29:48 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 427.
 1 SYSTEMPATH/Database/BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/CrudModel.php(7): CodeIgniter\Database\BaseConnection->query('SELECT * FROM users')
 3 APPPATH/Controllers/Crud.php(10): App\Models\CrudModel->listarNombres()
 4 SYSTEMPATH/CodeIgniter.php(934): App\Controllers\Crud->listado()
 5 SYSTEMPATH/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 6 SYSTEMPATH/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
